INSERT INTO CUADRILLASINTERNET (IDCUADRILLA, MIEMBROS, EMAIL, HABILITADO) VALUES (1, 'Lucciarini', '', 1)#
INSERT INTO CUADRILLASINTERNET (IDCUADRILLA, MIEMBROS, EMAIL, HABILITADO) VALUES (2, 'Ruiz', '', 1)#
INSERT INTO CUADRILLASINTERNET (IDCUADRILLA, MIEMBROS, EMAIL, HABILITADO) VALUES (3, 'Ale y Juan', '', 1)#
INSERT INTO CUADRILLASINTERNET (IDCUADRILLA, MIEMBROS, EMAIL, HABILITADO) VALUES (4, 'Facu y Fede', '', 1)#
INSERT INTO CUADRILLASINTERNET (IDCUADRILLA, MIEMBROS, EMAIL, HABILITADO) VALUES (5, 'Grupo nuevo', '', 1)#