INSERT INTO CUADRILLAS (IDCUADRILLA, MIEMBROS) VALUES (0, 'Lucciarini')#
INSERT INTO CUADRILLAS (IDCUADRILLA, MIEMBROS) VALUES (1, 'Ruiz')#
INSERT INTO CUADRILLAS (IDCUADRILLA, MIEMBROS) VALUES (2, 'Ale y Juan')#
INSERT INTO CUADRILLAS (IDCUADRILLA, MIEMBROS) VALUES (3, 'Facu y Fede')#
INSERT INTO CUADRILLAS (IDCUADRILLA, MIEMBROS) VALUES (4, 'Grupo nuevo')#