CREATE TABLE "CUADRILLASINTERNET" (
 "idcuadrilla" IDENTITY DEFAULT '1' NOT NULL,
 "miembros" VARCHAR(50),
 "email" VARCHAR(100),
 "habilitado" BIT
)#
CREATE UNIQUE NOT MODIFIABLE "Index_0" ON "CUADRILLAS" ( "idcuadrilla" )#
CREATE UNIQUE INDEX "Index_1" ON "CUADRILLAS" ( "miembros" )#
